#Minecraft server properties
#Fri Apr 14 16:14:13 EEST 2023
spawn-protection=0
query.port=50001
server-name=GRIEF
generator-settings=
force-gamemode=false
allow-nether=true
gamemode=0
broadcast-console-to-ops=false
enable-query=false
player-idle-timeout=0
difficulty=3
spawn-monsters=true
broadcast-rcon-to-ops=false
op-permission-level=0
pvp=true
snooper-enabled=false
level-type=DEFAULT
rcon.ip=0.0.0.0
hardcore=false
enable-command-block=false
max-players=200
network-compression-threshold=-1
resource-pack-sha1=
max-world-size=7000
rcon.port=
server-port=25565
debug=false
server-ip=0.0.0.0
spawn-npcs=true
allow-flight=false
defaultgamemode=survival
level-name=world
view-distance=6
server-id=GRIEF
resource-pack=
spawn-animals=true
white-list=false
rcon.password=EWWR87y23hedsifgbfsadAshMine
generate-structures=true
max-build-height=256
online-mode=false
level-seed=
prevent-proxy-connections=true
use-native-transport=true
enable-rcon=false
motd=Powered by FenixNodes.xyz
